server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base-project?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username:
    password:
  redis:
    host: redis-server
    port: 6379
    password: redis_password

logging:
  level:
    root: warn
    com.example: info
  file:
    path: /var/logs/base-project
    
# 关闭SQL打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl 